"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.timestamp_pb2
import lang.run_pb2
import program.program_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class ProjectEventStateRecord(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    T_FIELD_NUMBER: builtins.int
    STATE_FIELD_NUMBER: builtins.int
    @property
    def t(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def state(self) -> global___ProjectEventState: ...
    def __init__(self,
        *,
        t: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        state: typing.Optional[global___ProjectEventState] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["state",b"state","t",b"t"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["state",b"state","t",b"t"]) -> None: ...
global___ProjectEventStateRecord = ProjectEventStateRecord

class ProjectEventState(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ERROR_FIELD_NUMBER: builtins.int
    IGNORED_FIELD_NUMBER: builtins.int
    PENDING_FIELD_NUMBER: builtins.int
    LOADING_FIELD_NUMBER: builtins.int
    LOADED_FIELD_NUMBER: builtins.int
    RUNNING_FIELD_NUMBER: builtins.int
    WAITING_FIELD_NUMBER: builtins.int
    COMPLETED_FIELD_NUMBER: builtins.int
    @property
    def error(self) -> global___ErrorProjectEventState: ...
    @property
    def ignored(self) -> global___IgnoredProjectEventState: ...
    @property
    def pending(self) -> global___PendingProjectEventState: ...
    @property
    def loading(self) -> global___LoadingProjectEventState: ...
    @property
    def loaded(self) -> global___LoadedProjectEventState: ...
    @property
    def running(self) -> global___RunningProjectEventState: ...
    @property
    def waiting(self) -> global___WaitingProjectEventState: ...
    @property
    def completed(self) -> global___CompletedProjectEventState: ...
    def __init__(self,
        *,
        error: typing.Optional[global___ErrorProjectEventState] = ...,
        ignored: typing.Optional[global___IgnoredProjectEventState] = ...,
        pending: typing.Optional[global___PendingProjectEventState] = ...,
        loading: typing.Optional[global___LoadingProjectEventState] = ...,
        loaded: typing.Optional[global___LoadedProjectEventState] = ...,
        running: typing.Optional[global___RunningProjectEventState] = ...,
        waiting: typing.Optional[global___WaitingProjectEventState] = ...,
        completed: typing.Optional[global___CompletedProjectEventState] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["completed",b"completed","error",b"error","ignored",b"ignored","loaded",b"loaded","loading",b"loading","pending",b"pending","running",b"running","type",b"type","waiting",b"waiting"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["completed",b"completed","error",b"error","ignored",b"ignored","loaded",b"loaded","loading",b"loading","pending",b"pending","running",b"running","type",b"type","waiting",b"waiting"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["type",b"type"]) -> typing.Optional[typing_extensions.Literal["error","ignored","pending","loading","loaded","running","waiting","completed"]]: ...
global___ProjectEventState = ProjectEventState

class ErrorProjectEventState(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    RUN_SUMMARY_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    @property
    def run_summary(self) -> lang.run_pb2.RunSummary: ...
    error: typing.Text
    def __init__(self,
        *,
        run_summary: typing.Optional[lang.run_pb2.RunSummary] = ...,
        error: typing.Text = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["run_summary",b"run_summary"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["error",b"error","run_summary",b"run_summary"]) -> None: ...
global___ErrorProjectEventState = ErrorProjectEventState

class IgnoredProjectEventState(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    REASON_FIELD_NUMBER: builtins.int
    reason: typing.Text
    def __init__(self,
        *,
        reason: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["reason",b"reason"]) -> None: ...
global___IgnoredProjectEventState = IgnoredProjectEventState

class PendingProjectEventState(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    def __init__(self,
        ) -> None: ...
global___PendingProjectEventState = PendingProjectEventState

class LoadingProjectEventState(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    MAIN_PATH_FIELD_NUMBER: builtins.int
    @property
    def main_path(self) -> program.program_pb2.Path: ...
    def __init__(self,
        *,
        main_path: typing.Optional[program.program_pb2.Path] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["main_path",b"main_path"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["main_path",b"main_path"]) -> None: ...
global___LoadingProjectEventState = LoadingProjectEventState

class LoadedProjectEventState(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PATHS_FIELD_NUMBER: builtins.int
    @property
    def paths(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[program.program_pb2.Path]: ...
    def __init__(self,
        *,
        paths: typing.Optional[typing.Iterable[program.program_pb2.Path]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["paths",b"paths"]) -> None: ...
global___LoadedProjectEventState = LoadedProjectEventState

class RunningProjectEventState(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    def __init__(self,
        ) -> None: ...
global___RunningProjectEventState = RunningProjectEventState

class CompletedProjectEventState(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    RUN_SUMMARY_FIELD_NUMBER: builtins.int
    @property
    def run_summary(self) -> lang.run_pb2.RunSummary: ...
    def __init__(self,
        *,
        run_summary: typing.Optional[lang.run_pb2.RunSummary] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["run_summary",b"run_summary"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["run_summary",b"run_summary"]) -> None: ...
global___CompletedProjectEventState = CompletedProjectEventState

class WaitingProjectEventState(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAMES_FIELD_NUMBER: builtins.int
    RUN_SUMMARY_FIELD_NUMBER: builtins.int
    @property
    def names(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
    @property
    def run_summary(self) -> lang.run_pb2.RunSummary: ...
    def __init__(self,
        *,
        names: typing.Optional[typing.Iterable[typing.Text]] = ...,
        run_summary: typing.Optional[lang.run_pb2.RunSummary] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["run_summary",b"run_summary"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["names",b"names","run_summary",b"run_summary"]) -> None: ...
global___WaitingProjectEventState = WaitingProjectEventState
