// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: litterboxsvc/svc.proto

/*
Package litterboxsvc is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package litterboxsvc

import (
	"context"
	"io"
	"net/http"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/v2/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
)

// Suppress "imported and not used" errors
var _ codes.Code
var _ io.Reader
var _ status.Status
var _ = runtime.String
var _ = utilities.NewDoubleArray
var _ = metadata.Join

func request_LitterBox_Run_0(ctx context.Context, marshaler runtime.Marshaler, client LitterBoxClient, req *http.Request, pathParams map[string]string) (LitterBox_RunClient, runtime.ServerMetadata, error) {
	var protoReq RunRequest
	var metadata runtime.ServerMetadata

	newReader, berr := utilities.IOReaderFactory(req.Body)
	if berr != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", berr)
	}
	if err := marshaler.NewDecoder(newReader()).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	stream, err := client.Run(ctx, &protoReq)
	if err != nil {
		return nil, metadata, err
	}
	header, err := stream.Header()
	if err != nil {
		return nil, metadata, err
	}
	metadata.HeaderMD = header
	return stream, metadata, nil

}

// RegisterLitterBoxHandlerServer registers the http handlers for service LitterBox to "mux".
// UnaryRPC     :call LitterBoxServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
// Note that using this registration option will cause many gRPC library features to stop working. Consider using RegisterLitterBoxHandlerFromEndpoint instead.
func RegisterLitterBoxHandlerServer(ctx context.Context, mux *runtime.ServeMux, server LitterBoxServer) error {

	mux.Handle("POST", pattern_LitterBox_Run_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		err := status.Error(codes.Unimplemented, "streaming calls are not yet supported in the in-process transport")
		_, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
		return
	})

	return nil
}

// RegisterLitterBoxHandlerFromEndpoint is same as RegisterLitterBoxHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterLitterBoxHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.Dial(endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()

	return RegisterLitterBoxHandler(ctx, mux, conn)
}

// RegisterLitterBoxHandler registers the http handlers for service LitterBox to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterLitterBoxHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterLitterBoxHandlerClient(ctx, mux, NewLitterBoxClient(conn))
}

// RegisterLitterBoxHandlerClient registers the http handlers for service LitterBox
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "LitterBoxClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "LitterBoxClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "LitterBoxClient" to call the correct interceptors.
func RegisterLitterBoxHandlerClient(ctx context.Context, mux *runtime.ServeMux, client LitterBoxClient) error {

	mux.Handle("POST", pattern_LitterBox_Run_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		rctx, err := runtime.AnnotateContext(ctx, mux, req, "/autokitteh.litterbox.LitterBox/Run", runtime.WithHTTPPathPattern("/api/v1/litterbox/run"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_LitterBox_Run_0(rctx, inboundMarshaler, client, req, pathParams)
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_LitterBox_Run_0(ctx, mux, outboundMarshaler, w, req, func() (proto.Message, error) { return resp.Recv() }, mux.GetForwardResponseOptions()...)

	})

	return nil
}

var (
	pattern_LitterBox_Run_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2, 2, 3}, []string{"api", "v1", "litterbox", "run"}, ""))
)

var (
	forward_LitterBox_Run_0 = runtime.ForwardResponseStream
)
