# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: programsvc/svc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from validate import validate_pb2 as validate_dot_validate__pb2
from program import program_pb2 as program_dot_program__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14programsvc/svc.proto\x12\x15\x61utokitteh.programsvc\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17validate/validate.proto\x1a\x15program/program.proto\"o\n\x04\x46ile\x12&\n\x04path\x18\x01 \x01(\x0b\x32\x18.autokitteh.program.Path\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\x12.\n\nfetched_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\xd0\x01\n\rUpdateRequest\x12\x43\n\nproject_id\x18\x01 \x01(\tB/\xfa\x42,r*2(^[a-zA-Z][0-9a-zA-Z_-]+\\.[a-zA-Z0-9_-]+$\x12+\n\tmain_path\x18\x02 \x01(\x0b\x32\x18.autokitteh.program.Path\x12\x39\n\x05\x66iles\x18\x03 \x03(\x0b\x32\x1b.autokitteh.programsvc.FileB\r\xfa\x42\n\x92\x01\x07\"\x05\x8a\x01\x02\x10\x01\x12\x12\n\nonly_files\x18\x04 \x01(\x08\"\x10\n\x0eUpdateResponse\"\x89\x01\n\nGetRequest\x12\x43\n\nproject_id\x18\x01 \x01(\tB/\xfa\x42,r*2(^[a-zA-Z][0-9a-zA-Z_-]+\\.[a-zA-Z0-9_-]+$\x12\x36\n\x05paths\x18\x02 \x03(\x0b\x32\x18.autokitteh.program.PathB\r\xfa\x42\n\x92\x01\x07\"\x05\x8a\x01\x02\x10\x01\"\\\n\x0bGetResponse\x12\x39\n\x05\x66iles\x18\x01 \x03(\x0b\x32\x1b.autokitteh.programsvc.FileB\r\xfa\x42\n\x92\x01\x07\"\x05\x8a\x01\x02\x10\x01\x12\x12\n\nno_content\x18\x02 \x01(\x08\x32\x80\x02\n\x08Projects\x12\x7f\n\x06Update\x12$.autokitteh.programsvc.UpdateRequest\x1a%.autokitteh.programsvc.UpdateResponse\"(\x82\xd3\xe4\x93\x02\"\"\x1d/api/v1/programs/{project_id}:\x01*\x12s\n\x03Get\x12!.autokitteh.programsvc.GetRequest\x1a\".autokitteh.programsvc.GetResponse\"%\x82\xd3\xe4\x93\x02\x1f\"\x1d/api/v1/programs/{project_id}B%Z#go.autokitteh.dev/idl/go/programsvcb\x06proto3')



_FILE = DESCRIPTOR.message_types_by_name['File']
_UPDATEREQUEST = DESCRIPTOR.message_types_by_name['UpdateRequest']
_UPDATERESPONSE = DESCRIPTOR.message_types_by_name['UpdateResponse']
_GETREQUEST = DESCRIPTOR.message_types_by_name['GetRequest']
_GETRESPONSE = DESCRIPTOR.message_types_by_name['GetResponse']
File = _reflection.GeneratedProtocolMessageType('File', (_message.Message,), {
  'DESCRIPTOR' : _FILE,
  '__module__' : 'programsvc.svc_pb2'
  # @@protoc_insertion_point(class_scope:autokitteh.programsvc.File)
  })
_sym_db.RegisterMessage(File)

UpdateRequest = _reflection.GeneratedProtocolMessageType('UpdateRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEREQUEST,
  '__module__' : 'programsvc.svc_pb2'
  # @@protoc_insertion_point(class_scope:autokitteh.programsvc.UpdateRequest)
  })
_sym_db.RegisterMessage(UpdateRequest)

UpdateResponse = _reflection.GeneratedProtocolMessageType('UpdateResponse', (_message.Message,), {
  'DESCRIPTOR' : _UPDATERESPONSE,
  '__module__' : 'programsvc.svc_pb2'
  # @@protoc_insertion_point(class_scope:autokitteh.programsvc.UpdateResponse)
  })
_sym_db.RegisterMessage(UpdateResponse)

GetRequest = _reflection.GeneratedProtocolMessageType('GetRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETREQUEST,
  '__module__' : 'programsvc.svc_pb2'
  # @@protoc_insertion_point(class_scope:autokitteh.programsvc.GetRequest)
  })
_sym_db.RegisterMessage(GetRequest)

GetResponse = _reflection.GeneratedProtocolMessageType('GetResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETRESPONSE,
  '__module__' : 'programsvc.svc_pb2'
  # @@protoc_insertion_point(class_scope:autokitteh.programsvc.GetResponse)
  })
_sym_db.RegisterMessage(GetResponse)

_PROJECTS = DESCRIPTOR.services_by_name['Projects']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z#go.autokitteh.dev/idl/go/programsvc'
  _UPDATEREQUEST.fields_by_name['project_id']._options = None
  _UPDATEREQUEST.fields_by_name['project_id']._serialized_options = b'\372B,r*2(^[a-zA-Z][0-9a-zA-Z_-]+\\.[a-zA-Z0-9_-]+$'
  _UPDATEREQUEST.fields_by_name['files']._options = None
  _UPDATEREQUEST.fields_by_name['files']._serialized_options = b'\372B\n\222\001\007\"\005\212\001\002\020\001'
  _GETREQUEST.fields_by_name['project_id']._options = None
  _GETREQUEST.fields_by_name['project_id']._serialized_options = b'\372B,r*2(^[a-zA-Z][0-9a-zA-Z_-]+\\.[a-zA-Z0-9_-]+$'
  _GETREQUEST.fields_by_name['paths']._options = None
  _GETREQUEST.fields_by_name['paths']._serialized_options = b'\372B\n\222\001\007\"\005\212\001\002\020\001'
  _GETRESPONSE.fields_by_name['files']._options = None
  _GETRESPONSE.fields_by_name['files']._serialized_options = b'\372B\n\222\001\007\"\005\212\001\002\020\001'
  _PROJECTS.methods_by_name['Update']._options = None
  _PROJECTS.methods_by_name['Update']._serialized_options = b'\202\323\344\223\002\"\"\035/api/v1/programs/{project_id}:\001*'
  _PROJECTS.methods_by_name['Get']._options = None
  _PROJECTS.methods_by_name['Get']._serialized_options = b'\202\323\344\223\002\037\"\035/api/v1/programs/{project_id}'
  _FILE._serialized_start=158
  _FILE._serialized_end=269
  _UPDATEREQUEST._serialized_start=272
  _UPDATEREQUEST._serialized_end=480
  _UPDATERESPONSE._serialized_start=482
  _UPDATERESPONSE._serialized_end=498
  _GETREQUEST._serialized_start=501
  _GETREQUEST._serialized_end=638
  _GETRESPONSE._serialized_start=640
  _GETRESPONSE._serialized_end=732
  _PROJECTS._serialized_start=735
  _PROJECTS._serialized_end=991
# @@protoc_insertion_point(module_scope)
