"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing
import typing_extensions
import values.values_pb2

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class SetupRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    FILES_TXTAR_FIELD_NUMBER: builtins.int
    id: typing.Text
    files_txtar: builtins.bytes
    """in txtar format (see https://pkg.go.dev/golang.org/x/tools/txtar)."""

    def __init__(self,
        *,
        id: typing.Text = ...,
        files_txtar: builtins.bytes = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["files_txtar",b"files_txtar","id",b"id"]) -> None: ...
global___SetupRequest = SetupRequest

class SetupResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    id: typing.Text
    def __init__(self,
        *,
        id: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["id",b"id"]) -> None: ...
global___SetupResponse = SetupResponse

class GetRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    id: typing.Text
    def __init__(self,
        *,
        id: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["id",b"id"]) -> None: ...
global___GetRequest = GetRequest

class GetResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    FILES_TXTAR_FIELD_NUMBER: builtins.int
    files_txtar: builtins.bytes
    """in txtar format (see https://pkg.go.dev/golang.org/x/tools/txtar)."""

    def __init__(self,
        *,
        files_txtar: builtins.bytes = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["files_txtar",b"files_txtar"]) -> None: ...
global___GetResponse = GetResponse

class ScoopRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    id: typing.Text
    def __init__(self,
        *,
        id: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["id",b"id"]) -> None: ...
global___ScoopRequest = ScoopRequest

class ScoopResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    def __init__(self,
        ) -> None: ...
global___ScoopResponse = ScoopResponse

class LitterBoxEvent(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class ValuesEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: typing.Text
        @property
        def value(self) -> values.values_pb2.Value: ...
        def __init__(self,
            *,
            key: typing.Text = ...,
            value: typing.Optional[values.values_pb2.Value] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["value",b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["key",b"key","value",b"value"]) -> None: ...

    SRC_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    VALUES_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    ORIGINAL_ID_FIELD_NUMBER: builtins.int
    src: typing.Text
    type: typing.Text
    @property
    def values(self) -> google.protobuf.internal.containers.MessageMap[typing.Text, values.values_pb2.Value]:
        """values and data are mutually exclusive."""
        pass
    data: typing.Text
    """json data to be turned into values."""

    original_id: typing.Text
    def __init__(self,
        *,
        src: typing.Text = ...,
        type: typing.Text = ...,
        values: typing.Optional[typing.Mapping[typing.Text, values.values_pb2.Value]] = ...,
        data: typing.Text = ...,
        original_id: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["data",b"data","original_id",b"original_id","src",b"src","type",b"type","values",b"values"]) -> None: ...
global___LitterBoxEvent = LitterBoxEvent

class EventRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    EVENT_FIELD_NUMBER: builtins.int
    id: typing.Text
    @property
    def event(self) -> global___LitterBoxEvent: ...
    def __init__(self,
        *,
        id: typing.Text = ...,
        event: typing.Optional[global___LitterBoxEvent] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["event",b"event"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["event",b"event","id",b"id"]) -> None: ...
global___EventRequest = EventRequest

class RunRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    id: typing.Text
    def __init__(self,
        *,
        id: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["id",b"id"]) -> None: ...
global___RunRequest = RunRequest
