"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import event.project_state_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing
import typing_extensions
import values.values_pb2

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class SetupRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    name: typing.Text
    def __init__(self,
        *,
        name: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["name",b"name"]) -> None: ...
global___SetupRequest = SetupRequest

class SetupResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    id: typing.Text
    def __init__(self,
        *,
        id: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["id",b"id"]) -> None: ...
global___SetupResponse = SetupResponse

class ScoopRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    id: typing.Text
    def __init__(self,
        *,
        id: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["id",b"id"]) -> None: ...
global___ScoopRequest = ScoopRequest

class ScoopResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    def __init__(self,
        ) -> None: ...
global___ScoopResponse = ScoopResponse

class LitterBoxEvent(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class DataEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: typing.Text
        @property
        def value(self) -> values.values_pb2.Value: ...
        def __init__(self,
            *,
            key: typing.Text = ...,
            value: typing.Optional[values.values_pb2.Value] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["value",b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["key",b"key","value",b"value"]) -> None: ...

    SRC_BINDING_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    ORIGINAL_ID_FIELD_NUMBER: builtins.int
    src_binding: typing.Text
    type: typing.Text
    @property
    def data(self) -> google.protobuf.internal.containers.MessageMap[typing.Text, values.values_pb2.Value]: ...
    original_id: typing.Text
    def __init__(self,
        *,
        src_binding: typing.Text = ...,
        type: typing.Text = ...,
        data: typing.Optional[typing.Mapping[typing.Text, values.values_pb2.Value]] = ...,
        original_id: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["data",b"data","original_id",b"original_id","src_binding",b"src_binding","type",b"type"]) -> None: ...
global___LitterBoxEvent = LitterBoxEvent

class RunRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    SOURCE_FIELD_NUMBER: builtins.int
    EVENT_FIELD_NUMBER: builtins.int
    id: typing.Text
    """If id is empty, run will setup, use and scoop the litterbox by itself."""

    source: typing.Text
    @property
    def event(self) -> global___LitterBoxEvent: ...
    def __init__(self,
        *,
        id: typing.Text = ...,
        source: typing.Text = ...,
        event: typing.Optional[global___LitterBoxEvent] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["event",b"event"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["event",b"event","id",b"id","source",b"source"]) -> None: ...
global___RunRequest = RunRequest

class RunUpdate(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    STATE_FIELD_NUMBER: builtins.int
    id: typing.Text
    @property
    def state(self) -> event.project_state_pb2.ProjectEventStateRecord: ...
    def __init__(self,
        *,
        id: typing.Text = ...,
        state: typing.Optional[event.project_state_pb2.ProjectEventStateRecord] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["state",b"state"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["id",b"id","state",b"state"]) -> None: ...
global___RunUpdate = RunUpdate
