"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import google.protobuf.timestamp_pb2
import program.program_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class GetRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PROJECT_ID_FIELD_NUMBER: builtins.int
    PATH_FIELD_NUMBER: builtins.int
    RAW_PATH_FIELD_NUMBER: builtins.int
    OMIT_SOURCE_FIELD_NUMBER: builtins.int
    project_id: typing.Text
    @property
    def path(self) -> program.program_pb2.Path: ...
    raw_path: typing.Text
    """if set, overrides path."""

    omit_source: builtins.bool
    """if set, source is not returned."""

    def __init__(self,
        *,
        project_id: typing.Text = ...,
        path: typing.Optional[program.program_pb2.Path] = ...,
        raw_path: typing.Text = ...,
        omit_source: builtins.bool = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["path",b"path"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["omit_source",b"omit_source","path",b"path","project_id",b"project_id","raw_path",b"raw_path"]) -> None: ...
global___GetRequest = GetRequest

class GetResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PATH_FIELD_NUMBER: builtins.int
    SOURCE_FIELD_NUMBER: builtins.int
    FETCHED_AT_FIELD_NUMBER: builtins.int
    @property
    def path(self) -> program.program_pb2.Path: ...
    source: builtins.bytes
    @property
    def fetched_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(self,
        *,
        path: typing.Optional[program.program_pb2.Path] = ...,
        source: builtins.bytes = ...,
        fetched_at: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["fetched_at",b"fetched_at","path",b"path"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["fetched_at",b"fetched_at","path",b"path","source",b"source"]) -> None: ...
global___GetResponse = GetResponse
